// <auto-generated />
using System;
using DoAnWEB_HoSoBenhAnDienTu_Nhom3.Areas.Identity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoAnWEB_HoSoBenhAnDienTu_Nhom3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250623093317_addCTTT2")]
    partial class addCTTT2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", b =>
                {
                    b.Property<int>("MaBacSi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBacSi"));

                    b.Property<string>("ChuyenKhoa")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBacSi");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("BacSi", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Benh", b =>
                {
                    b.Property<int>("MaBenh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenh"));

                    b.Property<string>("MaICD")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NhomBenh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenBenh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaBenh");

                    b.ToTable("Benh", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", b =>
                {
                    b.Property<int>("MaBenhNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBenhNhan"));

                    b.Property<string>("DiUng")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaTaiKhoan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("NhomMau")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("SoBaoHiem")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaBenhNhan");

                    b.HasIndex("MaTaiKhoan")
                        .IsUnique();

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChanDoan", b =>
                {
                    b.Property<int>("MaChanDoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChanDoan"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("LoaiChanDoan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaBenh")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayChanDoan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.HasKey("MaChanDoan");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaBenh");

                    b.HasIndex("MaHoSo");

                    b.ToTable("ChanDoan", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiDinhXetNghiem", b =>
                {
                    b.Property<int>("MaChiDinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiDinh"));

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayChiDinh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenXetNghiem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaChiDinh");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaHoSo");

                    b.ToTable("ChiDinhXetNghiem", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiTietToaThuoc", b =>
                {
                    b.Property<int>("MaToaThuoc")
                        .HasColumnType("int");

                    b.Property<int>("MaThuoc")
                        .HasColumnType("int");

                    b.Property<string>("LieuLuong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChiTiet")
                        .HasColumnType("int");

                    b.Property<string>("SoLanUong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaToaThuoc", "MaThuoc");

                    b.HasIndex("MaThuoc");

                    b.ToTable("ChiTietToaThuoc", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.DonDieuTri", b =>
                {
                    b.Property<int>("MaDonDieuTri")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonDieuTri"));

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDonDieuTri")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDonDieuTri");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaHoSo");

                    b.ToTable("DonDieuTri", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HinhThucDieuTri", b =>
                {
                    b.Property<int>("MaHinhThuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhThuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenHinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHinhThuc");

                    b.ToTable("HinhThucDieuTri", (string)null);

                    b.HasData(
                        new
                        {
                            MaHinhThuc = 1,
                            TenHinhThuc = "Nội trú"
                        },
                        new
                        {
                            MaHinhThuc = 2,
                            TenHinhThuc = "Bán trú"
                        },
                        new
                        {
                            MaHinhThuc = 3,
                            TenHinhThuc = "Ngoại trú"
                        });
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<string>("LyDoNhapVien")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<int>("MaHinhThuc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayNhapVien")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuatVien")
                        .HasColumnType("datetime2");

                    b.Property<string>("TomTatBenhAn")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Đang điều trị");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaBenhNhan");

                    b.HasIndex("MaHinhThuc");

                    b.ToTable("HoSoBenhAn", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.KetQuaLamSang", b =>
                {
                    b.Property<int>("MaKetQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQua"));

                    b.Property<string>("BacSiKham")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChanDoan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HuyetAp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("NhietDo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("NhipTho")
                        .HasColumnType("int");

                    b.Property<int?>("NhipTim")
                        .HasColumnType("int");

                    b.Property<int?>("ThamKhamLamSangMaThamKham")
                        .HasColumnType("int");

                    b.HasKey("MaKetQua");

                    b.HasIndex("NgayKham");

                    b.HasIndex("ThamKhamLamSangMaThamKham");

                    b.HasIndex("MaBenhNhan", "NgayKham");

                    b.ToTable("KetQuaLamSang", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.KetQuaXetNghiem", b =>
                {
                    b.Property<int>("MaKetQuaXN")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKetQuaXN"));

                    b.Property<string>("GiaTriKetQua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhoangThamChieu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaChiDinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTraKetQua")
                        .HasColumnType("datetime2");

                    b.HasKey("MaKetQuaXN");

                    b.HasIndex("MaChiDinh");

                    b.ToTable("KetQuaXetNghiem", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa", (string)null);

                    b.HasData(
                        new
                        {
                            MaKhoa = 1,
                            MoTa = "Khoa điều trị các bệnh nội khoa",
                            TenKhoa = "Khoa Nội"
                        },
                        new
                        {
                            MaKhoa = 2,
                            MoTa = "Khoa phẫu thuật và điều trị ngoại khoa",
                            TenKhoa = "Khoa Ngoại"
                        },
                        new
                        {
                            MaKhoa = 3,
                            MoTa = "Khoa sản phụ khoa",
                            TenKhoa = "Khoa Sản"
                        },
                        new
                        {
                            MaKhoa = 4,
                            MoTa = "Khoa điều trị trẻ em",
                            TenKhoa = "Khoa Nhi"
                        },
                        new
                        {
                            MaKhoa = 5,
                            MoTa = "Khoa cấp cứu và hồi sức",
                            TenKhoa = "Khoa Cấp cứu"
                        });
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Property<int>("MaTaiKhoan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTaiKhoan"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTaiKhoan");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TaiKhoanNguoiDung", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ThamKhamLamSang", b =>
                {
                    b.Property<int>("MaThamKham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThamKham"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("KetQuaThamKham")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayThamKham")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrieuChung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaThamKham");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaHoSo");

                    b.ToTable("ThamKhamLamSang", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Thuoc", b =>
                {
                    b.Property<int>("MaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuoc"));

                    b.Property<string>("CachDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CongDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DonVi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("Gia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("HanSuDung")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoatChat")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuongTon")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MaThuoc");

                    b.ToTable("Thuoc", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ToaThuoc", b =>
                {
                    b.Property<int>("MaToaThuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToaThuoc"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("MaBacSi")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKeDon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaToaThuoc");

                    b.HasIndex("MaBacSi");

                    b.HasIndex("MaHoSo");

                    b.ToTable("ToaThuoc", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-user-id",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "STATIC-CONCURRENCY-STAMP-12345",
                            Email = "admin@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFn3KKyr22NmRH6beeOqz1rPC2f6m5es0/gSO2mstF637krSXqUjLfrbAS+lp8NI2Q==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "STATIC-SECURITY-STAMP-12345",
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-user-id",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Khoa", "Khoa")
                        .WithMany("BacSis")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.TaiKhoanNguoiDung", "TaiKhoan")
                        .WithOne("BacSi")
                        .HasForeignKey("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.TaiKhoanNguoiDung", "TaiKhoan")
                        .WithOne("BenhNhan")
                        .HasForeignKey("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", "MaTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChanDoan", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Benh", "Benh")
                        .WithMany("ChanDoans")
                        .HasForeignKey("MaBenh")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", "HoSo")
                        .WithMany()
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("Benh");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiDinhXetNghiem", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", "HoSo")
                        .WithMany("ChiDinhs")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiTietToaThuoc", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Thuoc", "Thuoc")
                        .WithMany("ChiTietToaThuocs")
                        .HasForeignKey("MaThuoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ToaThuoc", "ToaThuoc")
                        .WithMany("ChiTietToaThuocs")
                        .HasForeignKey("MaToaThuoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thuoc");

                    b.Navigation("ToaThuoc");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.DonDieuTri", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", "HoSo")
                        .WithMany("DonDieuTris")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", "BenhNhan")
                        .WithMany("HoSoBenhAn")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HinhThucDieuTri", "HinhThucDieuTri")
                        .WithMany("HoSoBenhAns")
                        .HasForeignKey("MaHinhThuc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BenhNhan");

                    b.Navigation("HinhThucDieuTri");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.KetQuaLamSang", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", "BenhNhan")
                        .WithMany("KetQuaLamSang")
                        .HasForeignKey("MaBenhNhan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ThamKhamLamSang", null)
                        .WithMany("KetQuas")
                        .HasForeignKey("ThamKhamLamSangMaThamKham");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.KetQuaXetNghiem", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiDinhXetNghiem", "ChiDinh")
                        .WithMany("KetQuas")
                        .HasForeignKey("MaChiDinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChiDinh");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ThamKhamLamSang", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", "HoSo")
                        .WithMany("ThamKhams")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ToaThuoc", b =>
                {
                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BacSi", "BacSi")
                        .WithMany()
                        .HasForeignKey("MaBacSi")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", "HoSo")
                        .WithMany()
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BacSi");

                    b.Navigation("HoSo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Benh", b =>
                {
                    b.Navigation("ChanDoans");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.BenhNhan", b =>
                {
                    b.Navigation("HoSoBenhAn");

                    b.Navigation("KetQuaLamSang");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ChiDinhXetNghiem", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HinhThucDieuTri", b =>
                {
                    b.Navigation("HoSoBenhAns");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.HoSoBenhAn", b =>
                {
                    b.Navigation("ChiDinhs");

                    b.Navigation("DonDieuTris");

                    b.Navigation("ThamKhams");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Khoa", b =>
                {
                    b.Navigation("BacSis");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.TaiKhoanNguoiDung", b =>
                {
                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ThamKhamLamSang", b =>
                {
                    b.Navigation("KetQuas");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.Thuoc", b =>
                {
                    b.Navigation("ChiTietToaThuocs");
                });

            modelBuilder.Entity("DoAnWEB_HoSoBenhAnDienTu_Nhom3.Models.ToaThuoc", b =>
                {
                    b.Navigation("ChiTietToaThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
